// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsjzvmuhuolyjxftdkvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzanp2bXVodW9seWp4ZnRka3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTc2MzQsImV4cCI6MjA2Mzc3MzYzNH0.aXPFr9ESJplhR-HhqPGM4Sh31aWqBEKlTxUUsunhevc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);